version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  helm: circleci/helm@2.0.1
  azure-aks: circleci/azure-aks@0.3.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  build-and-host-g2p-sandbox:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - run: rm -f helm/g2p-sandbox/Chart.lock helm/g2p-sandbox/requirements.lock helm/g2p-sandbox/charts/*
      - helm/install-helm-client:
          version: "v3.8.2"
      - run: "sed -i '6s/.*/appVersion: 0.0.0/' helm/g2p-sandbox/Chart.yaml"
      - run: "sed -i '7s/.*/version: 0.0.0/' helm/g2p-sandbox/Chart.yaml" 
      # - run: "sed -i '4s/.*/version: 0.0.0-SNAPSHOT/' helm/g2p-sandbox/requirements.yaml"
      # SED & replace dependency with 0.0.0
      - run: helm dep up helm/g2p-sandbox
      - run: helm package helm/g2p-sandbox
      - run: helm repo index .
      - run: echo "$CERT_FILE" | base64 --decode > b64encoded.pem
      - run: cat b64encoded.pem
      - run: chmod 600 b64encoded.pem
      - run: scp -v -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-0.0.0.tgz azureuser@172.174.237.43:~/
      - run: ssh -v -i b64encoded.pem -o StrictHostKeyChecking=No azureuser@172.174.237.43 sudo mv -t /usr/share/nginx/html/phee/0.0.0 index.yaml ph-ee-g2psandbox-0.0.0.tgz
  upgrade-helm-chart:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: "phee-mifos"
        type: string
      resource-group:
        description: "universe"
        type: string
    steps:
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: "phee-mifos"
          install-kubectl: true
          perform-login: true
          resource-group: "universe"
      - helm/install-helm-client:
          version: "v3.8.2"
      - run: helm ls --namespace=paymenthub
      - helm/upgrade-helm-chart:
          chart: "https://helm-charts.mifos.community/phee/0.0.0/ph-ee-g2psandbox-0.0.0.tgz"
          release-name: g2p-sandbox
          namespace: paymenthub
          recreate-pods: true
          add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
          wait: true
          timeout: "300s"    
workflows:
  deploy:
    jobs:
      - build-and-host-g2p-sandbox:
          context: 
            - Azure
            - Helm
            - slack
      - upgrade-helm-chart:
          cluster-name: "phee-mifos"
          resource-group: "universe"
          requires:
            - build-and-host-g2p-sandbox
          context: 
            - Azure
            - Helm
            - slack      

